### ISSUE TITLE
EarlyReactionBotBybitSwing: missing 1 required positional argument: 'before_entry_ids_json_path'

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/trading-bots#40]
Prosim o provereni chyby "missing 1 required positional argument: 'before_entry_ids_json_path'" nalezene v logu.

Stejna chyba i na pozicnim portfoliu.

Prostredi: PROD
Version: 1.2.0

**Ukazka chyby v logu**
```log
2023-07-21 10:58:27,352] p2577561 {__main__.py:28} INFO - 
---------------------------------------------------------------------
EarlyReactionBotBybitSwing - 1.2.0
---------------------------------------------------------------------

2023-07-21 10:58:27,353] p2577561 {__main__.py:37} ERROR - Error in app: 
Traceback (most recent call last):
  File "/home/prod1/app/trading-bots/trading-bots-1.2.0/trading_bots/__main__.py", line 32, in <module>
    bot = create_bot(bot_name, config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prod1/app/trading-bots/trading-bots-1.2.0/trading_bots/utils.py", line 31, in create_bot
    return EarlyReactionBotBybit(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prod1/app/trading-bots/trading-bots-1.2.0/trading_bots/early_reaction_bot_bybit.py", line 12, in __init__
    self.helper = EarlyReactionBotBybitHelper(self.pybit_client, self.config["base"]["beforeEntryIdsJsonPath"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EarlyReactionBotBybitHelper.__init__() missing 1 required positional argument: 'before_entry_ids_json_path'

```

Oprava bugu do vetve: hotfix/fixex_constructor_xxx nad vetvi master

**Comment by LucyQuantAnalyst** [comment]
# Analyza

Dle logu je chyba v konstruktoru v nespravnem predani poctu parametru

**EarlyReactionBotBybitHelper.__init__() missing 1 required positional argument: 'before_entry_ids_json_path'**

**Comment by LucyQuantAnalyst** [comment]
# Reseni

Jednalo se o pozustatek uprav z refaktoringu zapomnela jsem provest kontrolu volani konstruktoru

Chyba nastala v teto casti kodu:

```python
class EarlyReactionBotBybit(BybitBot):

    def __init__(self, config: dict):
        ...
        ...
        self.helper = EarlyReactionBotBybitHelper(self.pybit_client, self.config["base"]["beforeEntryIdsJsonPath"]) # byl pridan *self.config*, a pouze ponechan *self.pybit_client* a smazan *self.config["base"]["beforeEntryIdsJsonPath"]*
        ...
        ...
```

Dalsi cast chyby byla zde jelikoz se v helperu prestal pouzivat parametr *before_entry_ids_json_path*:

```python
class EarlyReactionBotBybitHelper:

    def __init__(self, config, pybit_client, before_entry_ids_json_path): # zde byl smazan parametr before_entry_ids_json_path 
       ...
       ...
        self.before_entry_ids_json_path = before_entry_ids_json_path # tento radek byl smazan
       ...
      ....
```
