### ISSUE TITLE
EquityLevelTraderBotCapitalHelper: chyba v umisteni tradu do platformy u tradu ID 1

### ISSUE THREAD

**Issue by LucyQuantAnalyst** [GeorgeQuantAnalyst/trading-bots#47]
Prosim o provereni proc se u ID 1 vyskytuje chyba:

```
Exception: Failed call place_trade on CapitalBrokerClient: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}
```

A jestli se spravne loguje tato hlaska:

```
raise Exception(f"HTTP Error {res.status}: {res.reason} with response: {response_text}")
```

Prostredi: PROD
Version: 1.2.1
Portfolio: Short

**Chyba v logu**

```log
2023-07-27 15:34:43,634] p2847522 {capital_broker_client.py:150} ERROR - Failed call POST method /api/v1/positions on api-capital.backend-capital.com REST api: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}
Traceback (most recent call last):
  File "/home/prod1/app/trading-bots/trading-bots-1.2.1/trading_bots/api/capital_broker_client.py", line 147, in place_trade
    raise Exception(f"HTTP Error {res.status}: {res.reason} with response: {response_text}")
Exception: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}
2023-07-27 15:34:43,635] p2847522 {equity_level_trader_bot_capital.py:104} ERROR - Failed place trade [OrderId: 1]: Failed call place_trade on CapitalBrokerClient: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}
Traceback (most recent call last):
  File "/home/prod1/app/trading-bots/trading-bots-1.2.1/trading_bots/helpers/equity_level_trader_bot_capital_helper.py", line 51, in place_trade
    self.capital_broker_client.place_trade(trade)
  File "/home/prod1/app/trading-bots/trading-bots-1.2.1/trading_bots/api/capital_broker_client.py", line 147, in place_trade
    raise Exception(f"HTTP Error {res.status}: {res.reason} with response: {response_text}")
Exception: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/prod1/app/trading-bots/trading-bots-1.2.1/trading_bots/equity_level_trader_bot_capital.py", line 100, in place_trade
    self.helper.place_trade(order)
  File "/home/prod1/app/trading-bots/trading-bots-1.2.1/trading_bots/helpers/equity_level_trader_bot_capital_helper.py", line 53, in place_trade
    raise Exception(f"Failed call place_trade on CapitalBrokerClient: {str(e)}")
Exception: Failed call place_trade on CapitalBrokerClient: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}

**Comment by GeorgeQuantAnalyst** [comment]
## Analyza

```log
2023-07-28 16:32:44,417] p2893035 {capital_broker_client.py:123} DEBUG - Trade: {'ticker': 'WDAY', 'direction': 'SELL', 'size': 0.0, 'guaranteedStop': False, 'stopDistance': 29.650000000000006, 'trailingStop': True, 'profitLevel': 202.51999999999998}
2023-07-28 16:32:44,418] p2893035 {capital_broker_client.py:135} DEBUG - Payload place_trade: {"epic": "WDAY", "direction": "SELL", "size": 0.0, "guaranteedStop": false, "stopDistance": 29.650000000000006, "trailingStop": true, "profitLevel": 202.51999999999998}
2023-07-28 16:32:44,493] p2893035 {capital_broker_client.py:145} DEBUG - Response place_trade: {"errorCode":"error.positive.createpositionrequest.size"}
2023-07-28 16:32:44,494] p2893035 {capital_broker_client.py:150} ERROR - Failed call POST method /api/v1/positions on api-capital.backend-capital.com REST api: HTTP Error 400:  with response: {"errorCode":"error.positive.createpositionrequest.size"}
Traceback (most recent call last):

```

**Comment by GeorgeQuantAnalyst** [comment]
## Reseni

Zrusena objednavka ze seznamu cekajich objednavek z vyse zminenych duvodu.
